test:
  stage: test
  image: ubuntu
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install numpy
    - pip install -r requirements.txt
    - python setup.py test

build:linux_x86_64:
  stage: build
  image: quay.io/pypa/manylinux1_x86_64
  script:
    - pip install numpy
    - bash .ci/python/build-wheels.sh
  artifacts:
      paths:
        - wheelhouse/
