<<<<<<< HEAD
=======
stages:
  - test
  - build
  - deploy

image: ubuntu

>>>>>>> master
test:
  stage: test
  image: ubuntu
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip python-matplotlib
    - pip install numpy
    # - pip install -r requirements.txt
    - pip install coverage
    - coverage run setup.py test
    - coverage report -m
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    expire_in: 3h
    paths:
      - testout
      - public

pages:
  stage: build
  script:
  - pip install sphinx sphinx-bootstrap-theme numpydoc # sphinxcontrib-versioning
  - make docs
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master