stages:
  - test
  - build
  - deploy

image: ubuntu

test:
  stage: test
  image: ubuntu
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip python-matplotlib
    - pip install numpy
    - pip install -r requirements.txt
    - python setup.py test

pages:
  stage: build
  script:
  - pip install sphinx sphinx-bootstrap-theme numpydoc # sphinxcontrib-versioning
  - make docs
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master

# build:linux_x86_64:
#   stage: deploy
#   image: quay.io/pypa/manylinux1_x86_64
#   script:
#     - yum install -y libpng-devel
#     - yum install -y freetype-devel
#     - bash .ci/python/build-wheels.sh
#   artifacts:
#       paths:
#         - wheelhouse/

# build:linux_i686:
#   stage: deploy
#   image: quay.io/pypa/manylinux1_i686
#   script:
#     - yum install -y libpng-devel
#     - yum install -y freetype-devel
#     - bash .ci/python/build-wheels.sh
#   artifacts:
#       paths:
#         - wheelhouse/
