stages:
  - test
  - build
  - deploy

image: ubuntu

test-python27:
  stage: test
  image: python:2.7
  script:
    - pip install numpy
    - pip install -r requirements.txt
    - python setup.py test

test-python36:
  stage: test
  image: python:3.6
  script:
    - pip install numpy
    - pip install -r requirements.txt
    - python setup.py test

test-python37:
  stage: test
  image: python:3.7
  script:
    - pip install numpy
    - pip install -r requirements.txt
    - python setup.py test

pages:
  image: python:3.6
  stage: build
  script:
  - pip install numpy
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - make docs
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
# Build receipe for standalone wheels on Linux
wheel-27:
  image: python:2.7
  stage: build
  script:
    - pip install wheel
    # Build wheel
    - python setup.py bdist_wheel --universal
  dependencies: []
  artifacts:
    expire_in: 3h
    paths:
      - dist

wheel-36:
  image: python:3.6
  stage: build
  script:
    - pip install wheel
    # Build wheel
    - python setup.py bdist_wheel --universal
  dependencies: []
  artifacts:
    expire_in: 3h
    paths:
      - dist

wheel-37:
  image: python:3.7
  stage: build
  script:
    - pip install wheel
    # Build wheel
    - python setup.py bdist_wheel --universal
  dependencies: []
  artifacts:
    expire_in: 3h
    paths:
      - dist

deploy:wheel:
  stage: deploy
  script:
    - pip install twine
    - twine upload dist/*
  only:
    - master@daniel-williams/heron
    - tags
